apiVersion: v1
kind: Service
metadata:
  name: filebrowser-service # Change this
  namespace: wordpress-tutorial # Change this
spec:
  ports:
  - port: 80
    targetPort: 80 # Change this
    protocol: TCP
  selector:
    app: filebrowser # Change this