apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wordpress-tutorial # Match with namespace
  name: wordpress # MARK C
  labels:
    app: wordpress # MARK C
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress # MARK C
  template:
    metadata:
      labels:
        app: wordpress # MARK C
    spec:
      containers:
      - name: wordpress
        image: wordpress
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql-service:3306
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        volumeMounts:
          - name: wordpress-persistent-storage
            mountPath: /var/www/html
        imagePullPolicy: Always
      restartPolicy: Always
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wordpress-storage